# Generated by Django 4.2.11 on 2026-08-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_notification_level_alter_notification_verb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='montly_reports/'),
        ),
    ]
