# Generated by Django 4.2.11 on 2026-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_notification_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='monthly_reports/'),
        ),
    ]
