# Generated by Django 4.2.11 on 2026-08-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_notification_month_notification_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysummarylog',
            unique_together={('year', 'month')},
        ),
        migrations.RemoveField(
            model_name='monthlysummarylog',
            name='user',
        ),
    ]
