# Generated by Django 4.2.11 on 2026-09-16 15:34
from django.db import migrations, models


def copy_remind_days_before(apps, schema_editor):
    Reminder = apps.get_model('expenses', 'Reminder')
    Reminder.objects.update(reminder1_days_before=models.F('remind_days_before'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_emailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254,
                help_text="The person's own email address, so the wish email can be sent directly to them.",
            ),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder1_days_before',
            field=models.PositiveIntegerField(
                default=0, help_text='First reminder. 0 = remind on the day itself',
            ),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder2_days_before',
            field=models.PositiveIntegerField(
                blank=True, null=True,
                help_text='Optional second reminder, e.g. a week earlier. Leave blank to send only one reminder.',
            ),
        ),
        migrations.RunPython(copy_remind_days_before, noop_reverse),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_days_before',
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='slot',
            field=models.CharField(
                choices=[('r1', 'Reminder 1'), ('r2', 'Reminder 2')],
                default='r1', max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together={('reminder', 'year', 'slot')},
        ),
    ]